"""create sources and news_items tables

Revision ID: 909bb72ee271
Revises: bb4fdd5465b4
Create Date: 2026-08-08 17:25:03.896434

Seeds `sources` from the same two feeds already allowlisted for
ResearchAgent's read_rss_feed tool (app/tools/research_tools.py's
RSS_ALLOWLIST) — see docs/08-modules/news-intelligence.md. Sources are
never client-writable; this migration is the only place they're created.
"""
import uuid
from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909bb72ee271'
down_revision = 'bb4fdd5465b4'
branch_labels = None
depends_on = None

SOURCES = [
    {
        "id": uuid.uuid4(),
        "key": "python_blog",
        "name": "Python Insider",
        "url": "https://blog.python.org/feeds/posts/default",
    },
    {
        "id": uuid.uuid4(),
        "key": "github_blog",
        "name": "The GitHub Blog",
        "url": "https://github.blog/feed/",
    },
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('news_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('link', sa.String(length=2000), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_items_link'), 'news_items', ['link'], unique=True)
    op.create_index(op.f('ix_news_items_source_id'), 'news_items', ['source_id'], unique=False)
    # ### end Alembic commands ###

    sources_table = sa.table(
        'sources',
        sa.column('id', sa.Uuid()),
        sa.column('key', sa.String()),
        sa.column('name', sa.String()),
        sa.column('url', sa.String()),
        sa.column('created_at', sa.DateTime(timezone=True)),
    )
    now = datetime.now(timezone.utc)
    op.bulk_insert(
        sources_table,
        [{**s, "created_at": now} for s in SOURCES],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_items_source_id'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_link'), table_name='news_items')
    op.drop_table('news_items')
    op.drop_table('sources')
    # ### end Alembic commands ###
